---
engines:
  brakeman:
    enabled: true
    exclude_fingerprints:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- app/assets/javascripts/fields/jsgrid.js