test:
  clients:
    default:
      database: skills_manager_test
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        max_pool_size: 5


development:
  clients:
    default:
      database: skills_manager_development
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        max_pool_size: 5


staging:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
      options:
        raise_not_found_error: false
        max_pool_size: 5


production:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
      options:
        raise_not_found_error: false
        max_pool_size: 5
