test:
  clients:
    default:
      database: nlu_cms_test<%= ENV['TEST_ENV_NUMBER'] %>
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false


development:
  clients:
    default:
      database: nlu_cms_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false


staging:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
  options:
    raise_not_found_error: false


production:
  clients:
    default:
      uri: <%= ENV[ 'MONGO_DB_URI'] %>
  options:
    raise_not_found_error: false

