# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1a850aebe81f315543401f265f847a312ec45e305e3cc06077fa606ab3f74e2fb1bb3a31126ee2cae29e0822132510de876a05a5e0553e04c4d9da42fa4775

test:
  secret_key_base: 4ad78961dea2db03a3636a699024d0616d8a0fcabc2d78c05e5553ae6c102b171a699c30d4619bb33a4417ffc73a97162f080661145e8e398539d70254ef0202

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
