ENV['RAILS_ENV'] = 'test'
ENV['RACK_ENV'] = 'test'
ENV[ 'I_AM_PLUS_ENV' ] = 'test'
ENV[ 'IDENTITY_SERVICE_URI' ] = 'https://test.identity.com'
ENV[ 'CLIENT_ID' ] = 'CLIENT_ID'
ENV[ 'CLIENT_SECRET' ] = 'CLIENT_SECRET'